// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: C:/Users/jose_/Documents/NetBeansProjects/Compilador/src/main/java/com/analisis/Lexer.flex

package com.analisis;

import com.analisis.objetos.analisis.ErrorManager;
import com.analisis.objetos.analisis.Pos;
import java_cup.runtime.*;
import java.util.ArrayList;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int JAVA = 2;
  public static final int PYTHON = 4;
  public static final int PRINCIPAL = 6;
  public static final int STRING = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\3\1\4\22\0\1\5"+
    "\1\6\1\7\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\11\25\1\26\1\27\1\30\1\31\1\32\2\0\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\45"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\45\1\63\1\0\1\64\1\0\1\65\1\0\1\66"+
    "\1\67\1\70\1\71\1\72\1\73\1\74\1\75\1\76"+
    "\1\45\1\77\1\100\1\101\1\102\1\103\1\104\1\45"+
    "\1\105\1\106\1\107\1\110\1\111\1\112\1\61\1\113"+
    "\1\45\1\114\1\115\1\116\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\2\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\15"+
    "\1\16\1\17\1\20\23\21\2\22\1\23\1\24\2\1"+
    "\1\11\1\13\1\25\1\16\1\17\15\21\1\26\1\1"+
    "\1\27\1\1\1\30\1\1\1\24\12\21\2\31\1\32"+
    "\1\33\1\24\1\5\1\34\3\21\1\35\1\36\7\21"+
    "\1\37\1\40\1\1\1\41\1\42\1\43\3\0\1\44"+
    "\1\0\1\45\1\46\1\47\1\21\1\50\5\21\1\51"+
    "\4\21\1\52\5\21\1\53\6\21\1\54\4\21\1\0"+
    "\1\55\1\0\1\56\1\57\1\60\20\21\1\53\3\0"+
    "\4\21\1\61\5\21\1\62\1\63\11\21\1\64\1\65"+
    "\1\66\1\0\1\67\1\70\2\0\1\71\1\0\2\44"+
    "\1\72\1\55\4\21\1\73\1\21\1\74\1\75\3\21"+
    "\1\24\1\21\1\23\4\21\1\76\5\21\1\0\1\77"+
    "\10\21\1\100\6\21\2\0\1\21\1\101\14\21\1\100"+
    "\3\21\2\0\1\102\1\0\1\103\1\104\2\21\1\105"+
    "\2\21\1\106\1\107\3\21\1\110\1\111\1\21\1\104"+
    "\2\21\1\112\4\21\1\105\5\21\1\113\1\21\2\0"+
    "\1\21\1\114\1\115\2\21\1\116\5\21\1\117\2\21"+
    "\2\0\10\21\1\120\4\21\1\121\1\122\1\21\1\123"+
    "\3\21\1\124\1\0\1\125\1\126\1\21\1\127\1\123"+
    "\1\130\2\21\1\131\1\132\1\133\2\21\1\134\2\21"+
    "\1\135\1\136\1\137\5\21\1\140\1\0\1\21\1\141"+
    "\1\21\1\142\5\21\1\0\1\143\1\0\1\144\1\145"+
    "\1\0\1\146\2\21\1\147\3\0\1\150\1\21\3\0"+
    "\1\151\1\0\1\152\4\0\1\125\4\0\1\144\2\0"+
    "\1\125\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[415];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\117\0\236\0\355\0\u013c\0\u018b\0\u01da\0\u018b"+
    "\0\u0229\0\u018b\0\u0278\0\u018b\0\u02c7\0\u018b\0\u018b\0\u018b"+
    "\0\u018b\0\u018b\0\u018b\0\u0316\0\u0365\0\u03b4\0\u0403\0\u0452"+
    "\0\u04a1\0\u04f0\0\u053f\0\u058e\0\u05dd\0\u062c\0\u067b\0\u06ca"+
    "\0\u0719\0\u0768\0\u07b7\0\u0806\0\u0855\0\u08a4\0\u08f3\0\u0942"+
    "\0\u0991\0\u09e0\0\u0a2f\0\u0a7e\0\u018b\0\u0acd\0\u0b1c\0\u0b6b"+
    "\0\u0bba\0\u0c09\0\u0c58\0\u0ca7\0\u018b\0\u0cf6\0\u0d45\0\u0d94"+
    "\0\u0de3\0\u0e32\0\u0e81\0\u0ed0\0\u0f1f\0\u0f6e\0\u0fbd\0\u100c"+
    "\0\u105b\0\u10aa\0\u10f9\0\u1148\0\u018b\0\u1197\0\u018b\0\u11e6"+
    "\0\u1235\0\u0b1c\0\u1284\0\u12d3\0\u1322\0\u1371\0\u13c0\0\u140f"+
    "\0\u145e\0\u14ad\0\u14fc\0\u154b\0\u159a\0\u018b\0\u15e9\0\u018b"+
    "\0\u018b\0\u018b\0\u0bba\0\u018b\0\u1638\0\u1687\0\u16d6\0\u018b"+
    "\0\u018b\0\u1725\0\u1774\0\u17c3\0\u1812\0\u1861\0\u18b0\0\u18ff"+
    "\0\u018b\0\u018b\0\u194e\0\u199d\0\u19ec\0\u1a3b\0\u1a8a\0\u1ad9"+
    "\0\u1b28\0\u1b77\0\u1bc6\0\u018b\0\u018b\0\u018b\0\u1c15\0\u053f"+
    "\0\u1c64\0\u1cb3\0\u1d02\0\u1d51\0\u1da0\0\u053f\0\u1def\0\u1e3e"+
    "\0\u1e8d\0\u1edc\0\u053f\0\u1f2b\0\u1f7a\0\u1fc9\0\u2018\0\u2067"+
    "\0\u053f\0\u20b6\0\u2105\0\u2154\0\u21a3\0\u21f2\0\u2241\0\u053f"+
    "\0\u2290\0\u22df\0\u232e\0\u237d\0\u23cc\0\u018b\0\u241b\0\u018b"+
    "\0\u018b\0\u018b\0\u246a\0\u24b9\0\u2508\0\u2557\0\u25a6\0\u25f5"+
    "\0\u2644\0\u2693\0\u26e2\0\u2731\0\u2780\0\u27cf\0\u281e\0\u286d"+
    "\0\u28bc\0\u290b\0\u018b\0\u11e6\0\u295a\0\u29a9\0\u29f8\0\u2a47"+
    "\0\u2a96\0\u2ae5\0\u2b34\0\u2b83\0\u2bd2\0\u2c21\0\u2c70\0\u2cbf"+
    "\0\u053f\0\u053f\0\u2d0e\0\u2d5d\0\u2dac\0\u2dfb\0\u2e4a\0\u2e99"+
    "\0\u2ee8\0\u2f37\0\u2f86\0\u018b\0\u018b\0\u018b\0\u2fd5\0\u018b"+
    "\0\u018b\0\u3024\0\u3073\0\u018b\0\u30c2\0\u018b\0\u3111\0\u1bc6"+
    "\0\u053f\0\u3160\0\u31af\0\u31fe\0\u324d\0\u053f\0\u329c\0\u053f"+
    "\0\u053f\0\u32eb\0\u333a\0\u3389\0\u053f\0\u33d8\0\u053f\0\u3427"+
    "\0\u3476\0\u34c5\0\u3514\0\u053f\0\u3563\0\u35b2\0\u3601\0\u3650"+
    "\0\u369f\0\u36ee\0\u018b\0\u373d\0\u378c\0\u37db\0\u382a\0\u3879"+
    "\0\u38c8\0\u3917\0\u3966\0\u39b5\0\u3a04\0\u3a53\0\u3aa2\0\u3af1"+
    "\0\u3b40\0\u3b8f\0\u3bde\0\u3c2d\0\u3c7c\0\u053f\0\u3ccb\0\u39b5"+
    "\0\u3d1a\0\u3d69\0\u3db8\0\u3e07\0\u3e56\0\u3ea5\0\u3ef4\0\u3f43"+
    "\0\u3f92\0\u3fe1\0\u053f\0\u4030\0\u407f\0\u40ce\0\u411d\0\u416c"+
    "\0\u018b\0\u41bb\0\u053f\0\u053f\0\u420a\0\u4259\0\u42a8\0\u42f7"+
    "\0\u4346\0\u053f\0\u053f\0\u4395\0\u43e4\0\u4433\0\u053f\0\u053f"+
    "\0\u4482\0\u44d1\0\u4520\0\u456f\0\u018b\0\u45be\0\u460d\0\u465c"+
    "\0\u46ab\0\u053f\0\u46fa\0\u4749\0\u4798\0\u47e7\0\u4836\0\u053f"+
    "\0\u4885\0\u48d4\0\u4923\0\u44d1\0\u053f\0\u053f\0\u4972\0\u49c1"+
    "\0\u053f\0\u4a10\0\u4a5f\0\u4aae\0\u4afd\0\u4b4c\0\u053f\0\u4b9b"+
    "\0\u4bea\0\u4c39\0\u4c88\0\u4cd7\0\u4d26\0\u4d75\0\u4dc4\0\u4e13"+
    "\0\u4e62\0\u4eb1\0\u4f00\0\u053f\0\u4f4f\0\u4f9e\0\u4fed\0\u503c"+
    "\0\u053f\0\u053f\0\u508b\0\u4f9e\0\u50da\0\u5129\0\u5178\0\u018b"+
    "\0\u51c7\0\u5216\0\u053f\0\u5265\0\u053f\0\u053f\0\u053f\0\u52b4"+
    "\0\u5303\0\u053f\0\u018b\0\u018b\0\u5352\0\u53a1\0\u053f\0\u53f0"+
    "\0\u543f\0\u053f\0\u053f\0\u053f\0\u548e\0\u54dd\0\u552c\0\u557b"+
    "\0\u55ca\0\u053f\0\u5619\0\u5668\0\u053f\0\u56b7\0\u053f\0\u5706"+
    "\0\u5755\0\u57a4\0\u57f3\0\u5842\0\u5891\0\u053f\0\u58e0\0\u053f"+
    "\0\u053f\0\u592f\0\u053f\0\u597e\0\u59cd\0\u053f\0\u5a1c\0\u5a6b"+
    "\0\u5aba\0\u053f\0\u5b09\0\u5b58\0\u5ba7\0\u5bf6\0\u053f\0\u5c45"+
    "\0\u018b\0\u5c94\0\u5ce3\0\u5d32\0\u5d81\0\u5dd0\0\u5e1f\0\u5e6e"+
    "\0\u5ebd\0\u5f0c\0\u018b\0\u5f5b\0\u5faa\0\u5ff9\0\u6048";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[415];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\7\1\11\1\7\1\6\1\12"+
    "\1\6\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\6\1\24\1\25\1\26\2\6\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\2\33\1\40\2\33\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\2\33\1\51\2\33\3\6\1\32"+
    "\1\33\1\52\1\35\1\36\1\53\2\33\1\54\1\33"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\2\33\1\51\1\33\4\6\1\7\1\55\1\7\1\56"+
    "\1\7\1\57\1\12\1\6\1\60\1\61\1\62\1\16"+
    "\1\17\1\20\1\63\1\22\1\64\1\6\1\24\1\25"+
    "\1\26\1\65\1\10\1\66\1\67\1\31\21\33\1\70"+
    "\6\33\3\6\1\33\1\71\1\72\1\73\1\74\1\75"+
    "\2\33\1\76\5\33\1\77\1\100\1\101\1\102\1\33"+
    "\1\103\1\104\1\33\1\105\1\106\1\107\1\6\1\110"+
    "\1\111\3\110\1\112\1\12\1\6\1\113\1\6\1\62"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\6\1\24"+
    "\1\25\1\26\1\65\1\6\1\66\1\67\1\31\30\33"+
    "\3\6\1\114\1\33\1\115\1\116\1\117\1\120\2\33"+
    "\1\121\3\33\1\122\1\123\1\124\1\125\4\33\1\104"+
    "\1\33\4\6\1\7\1\126\1\7\1\127\1\7\1\57"+
    "\1\130\1\131\1\132\1\133\1\62\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\134\1\24\1\25\1\26\1\65"+
    "\1\10\1\66\1\67\1\31\11\33\1\135\5\33\1\136"+
    "\4\33\1\137\3\33\1\140\1\141\1\6\1\33\1\71"+
    "\1\142\1\73\1\74\1\143\1\144\1\33\1\145\2\33"+
    "\1\146\2\33\1\147\1\33\1\150\2\33\1\103\1\104"+
    "\1\33\1\105\1\106\1\107\7\151\1\152\1\151\1\153"+
    "\32\151\1\154\5\151\1\155\4\151\1\156\37\151\120\0"+
    "\1\7\1\0\1\7\1\0\1\7\113\0\1\10\125\0"+
    "\1\157\105\0\117\160\16\0\1\161\4\0\1\162\115\0"+
    "\1\163\116\0\1\163\1\0\2\26\122\0\1\164\1\165"+
    "\114\0\1\164\1\0\1\166\115\0\1\166\111\0\2\33"+
    "\5\0\15\33\1\167\3\33\1\170\6\33\2\0\15\33"+
    "\1\167\3\33\1\170\5\33\27\0\2\33\5\0\30\33"+
    "\2\0\27\33\27\0\2\33\5\0\1\171\6\33\1\172"+
    "\6\33\1\173\11\33\2\0\1\33\1\171\6\33\1\172"+
    "\5\33\1\173\10\33\27\0\2\33\5\0\4\33\1\174"+
    "\3\33\1\175\5\33\1\176\11\33\2\0\5\33\1\174"+
    "\3\33\1\175\4\33\1\176\10\33\27\0\2\33\5\0"+
    "\13\33\1\177\1\33\1\200\12\33\2\0\13\33\1\177"+
    "\1\33\1\200\11\33\27\0\2\33\5\0\16\33\1\201"+
    "\4\33\1\202\4\33\2\0\16\33\1\201\4\33\1\202"+
    "\3\33\27\0\2\33\5\0\5\33\1\203\7\33\1\204"+
    "\12\33\2\0\6\33\1\203\6\33\1\204\11\33\27\0"+
    "\2\33\5\0\16\33\1\205\11\33\2\0\16\33\1\205"+
    "\10\33\27\0\2\33\5\0\16\33\1\206\11\33\2\0"+
    "\16\33\1\206\10\33\27\0\2\33\5\0\4\33\1\207"+
    "\11\33\1\210\11\33\2\0\5\33\1\207\10\33\1\210"+
    "\10\33\27\0\2\33\5\0\20\33\1\211\7\33\2\0"+
    "\20\33\1\211\6\33\27\0\2\33\5\0\23\33\1\212"+
    "\4\33\2\0\23\33\1\212\3\33\27\0\2\33\5\0"+
    "\4\33\1\213\23\33\2\0\5\33\1\213\21\33\27\0"+
    "\2\33\5\0\4\33\1\214\15\33\1\215\1\216\4\33"+
    "\2\0\5\33\1\214\14\33\1\215\1\216\3\33\27\0"+
    "\2\33\5\0\7\33\1\217\6\33\1\220\11\33\2\0"+
    "\10\33\1\217\5\33\1\220\10\33\27\0\2\33\5\0"+
    "\7\33\1\221\20\33\2\0\10\33\1\221\16\33\27\0"+
    "\2\33\5\0\1\171\6\33\1\172\6\33\1\173\11\33"+
    "\2\0\1\33\1\171\6\33\1\222\5\33\1\173\10\33"+
    "\27\0\2\33\5\0\16\33\1\201\4\33\1\202\4\33"+
    "\2\0\13\33\1\223\2\33\1\201\4\33\1\202\3\33"+
    "\27\0\2\33\5\0\5\33\1\203\7\33\1\204\12\33"+
    "\2\0\6\33\1\203\6\33\1\224\11\33\5\0\1\55"+
    "\145\0\1\165\76\0\1\225\117\0\1\226\104\0\117\227"+
    "\17\0\1\230\120\0\1\231\126\0\1\164\116\0\1\232"+
    "\111\0\2\33\5\0\30\33\2\0\26\33\1\233\27\0"+
    "\2\33\5\0\30\33\2\0\20\33\1\234\6\33\27\0"+
    "\2\33\5\0\30\33\2\0\1\33\1\235\6\33\1\236"+
    "\2\33\1\237\13\33\27\0\2\33\5\0\30\33\2\0"+
    "\5\33\1\240\10\33\1\176\10\33\27\0\2\33\5\0"+
    "\30\33\2\0\13\33\1\241\13\33\27\0\2\33\5\0"+
    "\30\33\2\0\13\33\1\242\2\33\1\243\10\33\27\0"+
    "\2\33\5\0\30\33\2\0\6\33\1\203\6\33\1\244"+
    "\11\33\27\0\2\33\5\0\30\33\2\0\23\33\1\245"+
    "\3\33\27\0\2\33\5\0\30\33\2\0\5\33\1\246"+
    "\21\33\27\0\2\33\5\0\30\33\2\0\25\33\1\247"+
    "\1\33\27\0\2\33\5\0\30\33\2\0\10\33\1\250"+
    "\16\33\27\0\2\33\5\0\30\33\2\0\16\33\1\251"+
    "\10\33\27\0\2\33\5\0\30\33\2\0\10\33\1\252"+
    "\16\33\120\0\1\253\2\0\1\254\1\111\3\254\112\0"+
    "\2\111\2\254\1\255\122\0\1\256\131\0\2\33\5\0"+
    "\30\33\2\0\15\33\1\257\11\33\27\0\2\33\5\0"+
    "\30\33\2\0\10\33\1\260\16\33\27\0\2\33\5\0"+
    "\30\33\2\0\5\33\1\261\21\33\27\0\2\33\5\0"+
    "\30\33\2\0\13\33\1\262\13\33\27\0\2\33\5\0"+
    "\30\33\2\0\13\33\1\223\2\33\1\243\10\33\27\0"+
    "\2\33\5\0\30\33\2\0\6\33\1\203\6\33\1\263"+
    "\11\33\27\0\2\33\5\0\30\33\2\0\16\33\1\264"+
    "\10\33\27\0\2\33\5\0\30\33\2\0\20\33\1\211"+
    "\6\33\27\0\2\33\5\0\30\33\2\0\1\33\1\265"+
    "\16\33\1\266\6\33\27\0\2\33\5\0\30\33\2\0"+
    "\1\33\1\267\3\33\1\246\21\33\5\0\1\126\140\0"+
    "\2\33\5\0\1\270\27\33\2\0\27\33\27\0\2\33"+
    "\5\0\27\33\1\271\2\0\27\33\27\0\2\33\5\0"+
    "\1\33\1\272\26\33\2\0\27\33\27\0\2\33\5\0"+
    "\30\33\2\0\1\33\1\235\6\33\1\273\2\33\1\274"+
    "\2\33\1\275\10\33\27\0\2\33\5\0\30\33\2\0"+
    "\13\33\1\276\2\33\1\243\10\33\27\0\2\33\5\0"+
    "\30\33\2\0\5\33\1\277\21\33\27\0\2\33\5\0"+
    "\30\33\2\0\6\33\1\203\6\33\1\300\11\33\27\0"+
    "\2\33\5\0\30\33\2\0\1\33\1\301\25\33\27\0"+
    "\2\33\5\0\30\33\2\0\20\33\1\302\2\33\1\245"+
    "\3\33\27\0\2\33\5\0\30\33\2\0\3\33\1\303"+
    "\21\33\1\247\1\33\73\0\1\304\1\305\1\0\1\306"+
    "\56\0\1\307\145\0\1\310\70\0\1\311\63\0\1\157"+
    "\1\0\1\157\1\0\1\157\36\0\1\312\12\0\1\313"+
    "\52\0\1\314\103\0\16\315\1\0\100\315\2\162\1\316"+
    "\1\162\1\317\112\162\24\0\1\163\1\320\115\0\2\33"+
    "\5\0\3\33\1\321\24\33\2\0\4\33\1\321\22\33"+
    "\27\0\2\33\5\0\21\33\1\322\6\33\2\0\21\33"+
    "\1\322\5\33\27\0\2\33\5\0\1\323\27\33\2\0"+
    "\1\33\1\323\25\33\27\0\2\33\5\0\15\33\1\324"+
    "\12\33\2\0\15\33\1\324\11\33\27\0\2\33\5\0"+
    "\2\33\1\325\25\33\2\0\3\33\1\325\23\33\27\0"+
    "\2\33\5\0\14\33\1\326\13\33\2\0\14\33\1\326"+
    "\12\33\27\0\2\33\5\0\21\33\1\327\6\33\2\0"+
    "\21\33\1\327\5\33\27\0\2\33\5\0\3\33\1\330"+
    "\24\33\2\0\4\33\1\330\22\33\27\0\2\33\5\0"+
    "\20\33\1\331\7\33\2\0\20\33\1\331\6\33\27\0"+
    "\2\33\5\0\15\33\1\332\12\33\2\0\15\33\1\332"+
    "\11\33\27\0\2\33\5\0\22\33\1\333\5\33\2\0"+
    "\22\33\1\333\4\33\27\0\2\33\5\0\16\33\1\334"+
    "\11\33\2\0\16\33\1\334\10\33\27\0\2\33\5\0"+
    "\3\33\1\335\24\33\2\0\4\33\1\335\22\33\27\0"+
    "\2\33\5\0\26\33\1\336\1\33\2\0\27\33\27\0"+
    "\2\33\5\0\22\33\1\337\5\33\2\0\22\33\1\337"+
    "\4\33\27\0\2\33\5\0\1\33\1\340\26\33\2\0"+
    "\2\33\1\340\24\33\27\0\2\33\5\0\22\33\1\341"+
    "\5\33\2\0\22\33\1\341\4\33\27\0\2\33\5\0"+
    "\13\33\1\342\14\33\2\0\13\33\1\342\13\33\27\0"+
    "\2\33\5\0\4\33\1\343\23\33\2\0\5\33\1\343"+
    "\21\33\27\0\2\33\5\0\1\33\1\344\26\33\2\0"+
    "\2\33\1\344\24\33\27\0\2\33\5\0\4\33\1\345"+
    "\23\33\2\0\5\33\1\345\21\33\27\0\2\33\5\0"+
    "\10\33\1\346\17\33\2\0\11\33\1\346\15\33\27\0"+
    "\2\33\5\0\1\323\27\33\2\0\1\33\1\347\25\33"+
    "\27\0\2\33\5\0\30\33\2\0\16\33\1\350\10\33"+
    "\27\0\2\33\5\0\22\33\1\333\5\33\2\0\22\33"+
    "\1\351\4\33\4\0\1\225\1\0\1\225\1\0\1\225"+
    "\44\0\1\352\57\0\1\353\127\0\2\33\5\0\30\33"+
    "\2\0\21\33\1\354\5\33\27\0\2\33\5\0\30\33"+
    "\2\0\5\33\1\355\21\33\27\0\2\33\5\0\30\33"+
    "\2\0\21\33\1\356\5\33\27\0\2\33\5\0\30\33"+
    "\2\0\1\33\1\357\25\33\27\0\2\33\5\0\30\33"+
    "\2\0\1\33\1\360\25\33\27\0\2\33\5\0\30\33"+
    "\2\0\6\33\1\361\20\33\27\0\2\33\5\0\30\33"+
    "\2\0\21\33\1\362\5\33\27\0\2\33\5\0\30\33"+
    "\2\0\16\33\1\363\10\33\27\0\2\33\5\0\30\33"+
    "\2\0\20\33\1\331\6\33\27\0\2\33\5\0\30\33"+
    "\2\0\22\33\1\364\4\33\27\0\2\33\5\0\30\33"+
    "\2\0\2\33\1\365\24\33\27\0\2\33\5\0\30\33"+
    "\2\0\22\33\1\366\4\33\27\0\2\33\5\0\30\33"+
    "\2\0\11\33\1\367\15\33\27\0\2\33\5\0\30\33"+
    "\2\0\11\33\1\370\15\33\27\0\2\33\5\0\30\33"+
    "\2\0\11\33\1\371\15\33\27\0\2\33\5\0\30\33"+
    "\2\0\11\33\1\372\15\33\4\0\1\254\1\111\2\254"+
    "\1\373\112\0\1\256\1\0\1\256\1\0\1\256\44\0"+
    "\1\374\70\0\2\33\5\0\30\33\2\0\4\33\1\321"+
    "\22\33\27\0\2\33\5\0\30\33\2\0\1\33\1\375"+
    "\25\33\27\0\2\33\5\0\30\33\2\0\6\33\1\376"+
    "\20\33\27\0\2\33\5\0\30\33\2\0\11\33\1\377"+
    "\7\33\1\362\5\33\27\0\2\33\5\0\30\33\2\0"+
    "\22\33\1\u0100\4\33\27\0\2\33\5\0\30\33\2\0"+
    "\22\33\1\337\4\33\27\0\2\33\5\0\30\33\2\0"+
    "\21\33\1\u0101\5\33\27\0\2\33\5\0\30\33\2\0"+
    "\11\33\1\u0102\15\33\27\0\2\33\5\0\30\33\2\0"+
    "\15\33\1\u0103\11\33\27\0\2\33\5\0\24\33\1\u0104"+
    "\3\33\2\0\27\33\27\0\2\33\5\0\30\33\2\0"+
    "\1\33\1\u0105\25\33\27\0\2\33\5\0\30\33\2\0"+
    "\20\33\1\u0106\6\33\27\0\2\33\5\0\30\33\2\0"+
    "\15\33\1\u0107\11\33\27\0\2\33\5\0\30\33\2\0"+
    "\16\33\1\u0108\10\33\27\0\2\33\5\0\30\33\2\0"+
    "\22\33\1\u0109\4\33\27\0\2\33\5\0\30\33\2\0"+
    "\3\33\1\u010a\16\33\1\u010b\4\33\27\0\2\33\5\0"+
    "\30\33\2\0\11\33\1\u010c\15\33\27\0\2\33\5\0"+
    "\30\33\2\0\11\33\1\u010d\15\33\27\0\2\33\5\0"+
    "\30\33\2\0\1\33\1\u010e\25\33\62\0\1\u010f\72\0"+
    "\1\u0110\117\0\1\u0111\62\0\16\315\1\u0112\100\315\2\0"+
    "\1\316\140\0\2\33\5\0\4\33\1\u0113\23\33\2\0"+
    "\5\33\1\u0113\21\33\27\0\2\33\5\0\20\33\1\u0114"+
    "\7\33\2\0\20\33\1\u0114\6\33\27\0\2\33\5\0"+
    "\21\33\1\u0115\6\33\2\0\21\33\1\u0115\5\33\27\0"+
    "\2\33\5\0\10\33\1\u0116\17\33\2\0\11\33\1\u0116"+
    "\15\33\27\0\2\33\5\0\4\33\1\u0117\23\33\2\0"+
    "\5\33\1\u0117\21\33\27\0\2\33\5\0\2\33\1\u0118"+
    "\25\33\2\0\3\33\1\u0118\23\33\27\0\2\33\5\0"+
    "\4\33\1\u0119\23\33\2\0\5\33\1\u0119\21\33\27\0"+
    "\2\33\5\0\17\33\1\u011a\10\33\2\0\17\33\1\u011a"+
    "\7\33\27\0\2\33\5\0\22\33\1\u011b\5\33\2\0"+
    "\22\33\1\u011b\4\33\27\0\2\33\5\0\13\33\1\u011c"+
    "\14\33\2\0\13\33\1\u011c\13\33\27\0\2\33\5\0"+
    "\23\33\1\u011d\4\33\2\0\23\33\1\u011d\3\33\27\0"+
    "\2\33\5\0\4\33\1\u011e\23\33\2\0\5\33\1\u011e"+
    "\21\33\27\0\2\33\5\0\17\33\1\u011f\10\33\2\0"+
    "\17\33\1\u011f\7\33\27\0\2\33\5\0\15\33\1\u0120"+
    "\12\33\2\0\15\33\1\u0120\11\33\27\0\2\33\5\0"+
    "\13\33\1\u0121\14\33\2\0\13\33\1\u0121\13\33\27\0"+
    "\2\33\5\0\20\33\1\u0114\7\33\2\0\20\33\1\u0122"+
    "\6\33\27\0\2\33\5\0\30\33\2\0\1\33\1\u0123"+
    "\25\33\27\0\2\33\5\0\4\33\1\u0119\23\33\2\0"+
    "\5\33\1\u0119\3\33\1\u0124\15\33\65\0\1\u0125\60\0"+
    "\2\33\5\0\30\33\2\0\22\33\1\u0126\4\33\27\0"+
    "\2\33\5\0\30\33\2\0\1\33\1\u0127\25\33\27\0"+
    "\2\33\5\0\30\33\2\0\5\33\1\u0113\21\33\27\0"+
    "\2\33\5\0\30\33\2\0\20\33\1\u0122\6\33\27\0"+
    "\2\33\5\0\30\33\2\0\21\33\1\u0128\5\33\27\0"+
    "\2\33\5\0\30\33\2\0\1\33\1\u0129\25\33\27\0"+
    "\2\33\5\0\30\33\2\0\5\33\1\u012a\21\33\27\0"+
    "\2\33\5\0\30\33\2\0\1\33\1\u012b\25\33\27\0"+
    "\2\33\5\0\30\33\2\0\11\33\1\u0124\15\33\27\0"+
    "\2\33\5\0\30\33\2\0\13\33\1\u012c\13\33\27\0"+
    "\2\33\5\0\30\33\2\0\23\33\1\u012d\3\33\27\0"+
    "\2\33\5\0\30\33\2\0\22\33\1\u012e\4\33\27\0"+
    "\2\33\5\0\30\33\2\0\21\33\1\u012f\5\33\27\0"+
    "\2\33\5\0\30\33\2\0\4\33\1\u0130\22\33\27\0"+
    "\2\33\5\0\30\33\2\0\13\33\1\u0131\13\33\4\0"+
    "\1\254\1\111\2\254\1\u0132\164\0\1\u0133\67\0\2\33"+
    "\5\0\30\33\2\0\20\33\1\u0134\6\33\27\0\2\33"+
    "\5\0\30\33\2\0\6\33\1\u0135\20\33\27\0\2\33"+
    "\5\0\30\33\2\0\21\33\1\u0136\5\33\27\0\2\33"+
    "\5\0\30\33\2\0\15\33\1\u0137\11\33\27\0\2\33"+
    "\5\0\30\33\2\0\7\33\1\u0138\17\33\27\0\2\33"+
    "\5\0\1\u0139\27\33\2\0\27\33\27\0\2\33\5\0"+
    "\30\33\2\0\20\33\1\u0114\6\33\27\0\2\33\5\0"+
    "\30\33\2\0\21\33\1\u013a\5\33\27\0\2\33\5\0"+
    "\30\33\2\0\21\33\1\u013b\5\33\27\0\2\33\5\0"+
    "\30\33\2\0\1\33\1\u013c\25\33\27\0\2\33\5\0"+
    "\30\33\2\0\3\33\1\u013d\23\33\27\0\2\33\5\0"+
    "\30\33\2\0\13\33\1\u013e\13\33\27\0\2\33\5\0"+
    "\30\33\2\0\15\33\1\u013f\11\33\27\0\2\33\5\0"+
    "\30\33\2\0\15\33\1\u0140\11\33\27\0\2\33\5\0"+
    "\30\33\2\0\15\33\1\u0141\11\33\36\0\1\u0142\142\0"+
    "\1\u0143\37\0\16\315\1\u0112\4\315\1\316\73\315\24\0"+
    "\2\33\5\0\16\33\1\u0144\11\33\2\0\16\33\1\u0144"+
    "\10\33\27\0\2\33\5\0\14\33\1\u0145\13\33\2\0"+
    "\14\33\1\u0145\12\33\27\0\2\33\5\0\10\33\1\u0146"+
    "\17\33\2\0\11\33\1\u0146\15\33\27\0\2\33\5\0"+
    "\22\33\1\u0147\5\33\2\0\22\33\1\u0147\4\33\27\0"+
    "\2\33\5\0\6\33\1\u0148\21\33\2\0\7\33\1\u0148"+
    "\17\33\27\0\2\33\5\0\10\33\1\u0149\17\33\2\0"+
    "\11\33\1\u0149\15\33\27\0\2\33\5\0\20\33\1\u014a"+
    "\7\33\2\0\20\33\1\u014a\6\33\27\0\2\33\5\0"+
    "\2\33\1\u014b\25\33\2\0\3\33\1\u014b\23\33\27\0"+
    "\2\33\5\0\4\33\1\u014c\23\33\2\0\5\33\1\u014c"+
    "\21\33\27\0\2\33\5\0\30\33\2\0\11\33\1\u014d"+
    "\15\33\27\0\2\33\5\0\30\33\2\0\22\33\1\u014e"+
    "\4\33\27\0\2\33\5\0\30\33\2\0\15\33\1\u014f"+
    "\11\33\27\0\2\33\5\0\30\33\2\0\5\33\1\u0150"+
    "\21\33\27\0\2\33\5\0\30\33\2\0\12\33\1\u0151"+
    "\14\33\27\0\2\33\5\0\30\33\2\0\21\33\1\u0152"+
    "\5\33\27\0\2\33\5\0\30\33\2\0\23\33\1\u0153"+
    "\3\33\27\0\2\33\5\0\30\33\2\0\22\33\1\u0154"+
    "\4\33\27\0\2\33\5\0\30\33\2\0\11\33\1\u0155"+
    "\15\33\27\0\2\33\5\0\30\33\2\0\20\33\1\u0156"+
    "\6\33\27\0\2\33\5\0\30\33\2\0\3\33\1\u0157"+
    "\23\33\25\0\1\u0158\1\0\2\33\5\0\30\33\2\0"+
    "\27\33\27\0\2\33\5\0\30\33\2\0\5\33\1\u014c"+
    "\21\33\4\0\1\254\1\111\2\254\1\111\162\0\1\u0159"+
    "\71\0\2\33\5\0\30\33\2\0\22\33\1\u015a\4\33"+
    "\27\0\2\33\5\0\30\33\2\0\5\33\1\u015b\21\33"+
    "\27\0\2\33\5\0\30\33\2\0\3\33\1\u015c\23\33"+
    "\27\0\2\33\5\0\30\33\2\0\22\33\1\u015d\4\33"+
    "\27\0\2\33\5\0\30\33\2\0\22\33\1\u015e\4\33"+
    "\27\0\2\33\5\0\30\33\2\0\10\33\1\u015f\16\33"+
    "\27\0\2\33\5\0\30\33\2\0\23\33\1\u0160\3\33"+
    "\27\0\2\33\5\0\30\33\2\0\22\33\1\u0161\4\33"+
    "\27\0\2\33\5\0\30\33\2\0\6\33\1\u0162\20\33"+
    "\25\0\1\u0163\127\0\1\u0164\107\0\2\33\5\0\13\33"+
    "\1\u0165\14\33\2\0\13\33\1\u0165\13\33\27\0\2\33"+
    "\5\0\1\u0166\27\33\2\0\1\33\1\u0166\25\33\27\0"+
    "\2\33\5\0\5\33\1\u0167\22\33\2\0\6\33\1\u0167"+
    "\20\33\27\0\2\33\5\0\10\33\1\u0168\17\33\2\0"+
    "\11\33\1\u0168\15\33\27\0\2\33\5\0\4\33\1\u0169"+
    "\23\33\2\0\5\33\1\u0169\21\33\27\0\2\33\5\0"+
    "\2\33\1\u016a\25\33\2\0\3\33\1\u016a\23\33\27\0"+
    "\2\33\5\0\15\33\1\u016b\12\33\2\0\15\33\1\u016b"+
    "\11\33\27\0\2\33\5\0\22\33\1\u016c\5\33\2\0"+
    "\22\33\1\u016c\4\33\27\0\2\33\5\0\30\33\2\0"+
    "\15\33\1\u016d\11\33\27\0\2\33\5\0\30\33\2\0"+
    "\11\33\1\u016e\15\33\27\0\2\33\5\0\30\33\2\0"+
    "\17\33\1\u016f\7\33\27\0\2\33\5\0\30\33\2\0"+
    "\14\33\1\u0170\12\33\27\0\2\33\5\0\30\33\2\0"+
    "\13\33\1\u0171\13\33\27\0\2\33\5\0\30\33\2\0"+
    "\3\33\1\u016a\23\33\27\0\2\33\5\0\30\33\2\0"+
    "\15\33\1\u016b\11\33\27\0\2\33\5\0\30\33\2\0"+
    "\10\33\1\u0172\16\33\44\0\1\u0173\101\0\2\33\5\0"+
    "\30\33\2\0\13\33\1\u0174\13\33\27\0\2\33\5\0"+
    "\30\33\2\0\20\33\1\u0175\6\33\27\0\2\33\5\0"+
    "\30\33\2\0\4\33\1\u0176\22\33\27\0\2\33\5\0"+
    "\30\33\2\0\6\33\1\u0177\20\33\27\0\2\33\5\0"+
    "\4\33\1\u0178\23\33\2\0\5\33\1\u0178\21\33\27\0"+
    "\2\33\5\0\13\33\1\u015e\14\33\2\0\13\33\1\u015e"+
    "\13\33\27\0\2\33\5\0\16\33\1\u0179\11\33\2\0"+
    "\16\33\1\u0179\10\33\27\0\2\33\5\0\20\33\1\u010b"+
    "\7\33\2\0\20\33\1\u010b\6\33\27\0\2\33\5\0"+
    "\30\33\2\0\17\33\1\u017a\7\33\27\0\2\33\5\0"+
    "\30\33\2\0\15\33\1\u017b\11\33\27\0\2\33\5\0"+
    "\30\33\2\0\23\33\1\u017c\3\33\25\0\1\u017d\1\0"+
    "\2\33\5\0\30\33\2\0\27\33\27\0\2\33\5\0"+
    "\30\33\2\0\22\33\1\u017e\4\33\56\0\1\u017f\67\0"+
    "\2\33\5\0\30\33\2\0\15\33\1\u0180\11\33\27\0"+
    "\2\33\5\0\30\33\2\0\5\33\1\u0181\21\33\25\0"+
    "\1\u0182\1\0\2\33\5\0\30\33\2\0\27\33\27\0"+
    "\2\33\5\0\15\33\1\u0183\12\33\2\0\15\33\1\u0183"+
    "\11\33\27\0\2\33\5\0\30\33\2\0\23\33\1\u0184"+
    "\3\33\27\0\2\33\5\0\30\33\2\0\17\33\1\u0185"+
    "\7\33\27\0\2\33\5\0\30\33\2\0\22\33\1\u0186"+
    "\4\33\106\0\1\u0187\46\0\1\u0188\143\0\1\u0189\31\0"+
    "\1\u0189\30\0\2\33\5\0\30\33\2\0\22\33\1\u018a"+
    "\4\33\27\0\2\33\5\0\30\33\2\0\23\33\1\u018b"+
    "\3\33\113\0\1\u018c\55\0\1\u018d\122\0\1\u018e\31\0"+
    "\1\u018e\35\0\2\33\5\0\30\33\2\0\22\33\1\u018f"+
    "\4\33\112\0\1\u0190\42\0\1\u0191\126\0\1\u0192\32\0"+
    "\1\u0192\42\0\1\u0193\151\0\1\u0194\31\0\1\u0194\113\0"+
    "\1\u0195\51\0\1\u0196\32\0\1\u0196\131\0\1\u0197\57\0"+
    "\1\u0198\31\0\1\u0198\114\0\1\u0199\63\0\1\u019a\4\0"+
    "\1\u019b\25\0\1\u019a\3\0\1\u019b\116\0\1\u019c\64\0"+
    "\1\u019d\31\0\1\u019d\123\0\1\u019e\46\0\1\u019b\32\0"+
    "\1\u019b\124\0\1\u019f\120\0\1\u019b\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[24727];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\6\11\31\1\1\11\7\1\1\11\17\1\1\11"+
    "\1\1\1\11\16\1\1\11\1\1\3\11\1\1\1\11"+
    "\3\1\2\11\7\1\2\11\4\1\3\0\1\1\1\0"+
    "\3\11\36\1\1\0\1\11\1\0\3\11\20\1\1\11"+
    "\3\0\25\1\3\11\1\0\2\11\2\0\1\11\1\0"+
    "\1\11\33\1\1\0\1\11\17\1\2\0\22\1\2\0"+
    "\1\11\1\0\22\1\1\11\14\1\2\0\16\1\2\0"+
    "\24\1\1\11\1\0\11\1\2\11\16\1\1\0\11\1"+
    "\1\0\1\1\1\0\2\1\1\0\4\1\3\0\2\1"+
    "\3\0\1\1\1\0\1\11\4\0\1\1\4\0\1\11"+
    "\2\0\1\1\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[415];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private StringBuffer cadena = new StringBuffer();
    private ArrayList<Integer> integers = new ArrayList<>();
    private ErrorManager errores = new ErrorManager();
    private boolean analizando;
    private boolean verificarident = false;
    private int seccionActual=0;

    private Symbol symbol(int linea, int columna, String lexema, int type){
        Symbol simbolo = new Symbol(type, linea, columna, lexema);
        escribirSimbolo(simbolo);
        return simbolo;
    }

    private Symbol symbol(int linea, int columna, int type){
        Symbol simbolo = new Symbol(type,linea,columna);
        escribirSimbolo(simbolo);
        return simbolo;
    }

    private Symbol symbol(String value, int tam) {
        if(verificarident){
            int i = integers.get(integers.size()-1);
            if(i>(tam-1-value.lastIndexOf('\n'))){
                integers.remove(integers.size()-1);
                this.yypushback(tam - value.lastIndexOf('\n'));
                Symbol simbolo = new Symbol(sym.DEDENT, yyline+1, yycolumn+1, value);
                escribirSimbolo(simbolo);
                return simbolo;
            } else if(i< (tam-1-value.lastIndexOf('\n'))) {
                integers.add(tam-1-value.lastIndexOf('\n'));
                verificarident = false;
                Symbol simbolo = new Symbol(sym.IDENT, yyline+1, yycolumn+1, value);
                escribirSimbolo(simbolo);
                return simbolo;
            } else {
                verificarident = false;
                return null;
            }
        } else {
            this.yypushback(tam - value.lastIndexOf('\n'));
            verificarident = true;
            Symbol simbolo = new Symbol(sym.NEWLINE, yyline+1, yycolumn+1, value);
            escribirSimbolo(simbolo);
            return simbolo;
        }
    }

    public boolean isAnalizando(){ return analizando; }

    private void escribirSimbolo(Symbol simbolo){
        System.out.println("Simbolo{\n    cadena:"+simbolo.value+"\n    tipo:"+sym.terminalNames[simbolo.sym]+"\n    linea:"+simbolo.left+"\n    columna:"+simbolo.right+"\n}\n");
    }

    private void cambiarEstado(){
        switch(seccionActual){
            case 0: yybegin(YYINITIAL); break;
            case 1: yybegin(JAVA); break;
            case 2: yybegin(PYTHON); break;
            case 3: yybegin(PRINCIPAL); break;
        }
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      seccionActual = 0;
    integers.add(0);
    analizando = true;
    yybegin(YYINITIAL);
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    analizando = false;
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.agregarError("Lexico",yytext(),"Caracter no aceptado",new Pos(yyline+1, yycolumn+1));
            }
            // fall through
          case 107: break;
          case 2:
            { /* Ignora los espacios en blanco */
            }
            // fall through
          case 108: break;
          case 3:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.FIN_LINEA);
            }
            // fall through
          case 109: break;
          case 4:
            { yybegin(STRING);
            }
            // fall through
          case 110: break;
          case 5:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.AMPERSON);
            }
            // fall through
          case 111: break;
          case 6:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PAR_A);
            }
            // fall through
          case 112: break;
          case 7:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PAR_C);
            }
            // fall through
          case 113: break;
          case 8:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.POR);
            }
            // fall through
          case 114: break;
          case 9:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MAS);
            }
            // fall through
          case 115: break;
          case 10:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.COMA);
            }
            // fall through
          case 116: break;
          case 11:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MENOS);
            }
            // fall through
          case 117: break;
          case 12:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.DIV);
            }
            // fall through
          case 118: break;
          case 13:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.ENTERO);
            }
            // fall through
          case 119: break;
          case 14:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MENOR);
            }
            // fall through
          case 120: break;
          case 15:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.IGUAL);
            }
            // fall through
          case 121: break;
          case 16:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MAYOR);
            }
            // fall through
          case 122: break;
          case 17:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.ID);
            }
            // fall through
          case 123: break;
          case 18:
            { /* Ignora los saltos de linea */
            }
            // fall through
          case 124: break;
          case 19:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.NOT);
            }
            // fall through
          case 125: break;
          case 20:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MOD);
            }
            // fall through
          case 126: break;
          case 21:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.DOS_PUNTOS);
            }
            // fall through
          case 127: break;
          case 22:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.LLAVE_A);
            }
            // fall through
          case 128: break;
          case 23:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.LLAVE_C);
            }
            // fall through
          case 129: break;
          case 24:
            { Symbol sim = symbol(yytext(), yytext().length()); 
                                                            if(sim!=null){
                                                                return sim;
                                                            }
            }
            // fall through
          case 130: break;
          case 25:
            { /* ignora los saltos de linea */
            }
            // fall through
          case 131: break;
          case 26:
            { cadena.setLength(0); yybegin(STRING);
            }
            // fall through
          case 132: break;
          case 27:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.HASHTAG);
            }
            // fall through
          case 133: break;
          case 28:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PUNTO);
            }
            // fall through
          case 134: break;
          case 29:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.COR_A);
            }
            // fall through
          case 135: break;
          case 30:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.COR_C);
            }
            // fall through
          case 136: break;
          case 31:
            { cadena.append(yytext());
            }
            // fall through
          case 137: break;
          case 32:
            { cambiarEstado();  
                                                if(cadena.length() > 0){
                                                    String lexema = cadena.toString();
                                                    cadena.setLength(0);
                                                    return symbol(yyline+1, (yycolumn+1)-lexema.length(), lexema, (lexema.length() > 1)? sym.CADENA : sym.CARACTER);
                                                }
            }
            // fall through
          case 138: break;
          case 33:
            { cadena.append("J");
            }
            // fall through
          case 139: break;
          case 34:
            { cadena.append("P");
            }
            // fall through
          case 140: break;
          case 35:
            { cadena.append("V");
            }
            // fall through
          case 141: break;
          case 36:
            { /* se ignoran los comentarios */
            }
            // fall through
          case 142: break;
          case 37:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MENORIGUAL);
            }
            // fall through
          case 143: break;
          case 38:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.DISTINTO);
            }
            // fall through
          case 144: break;
          case 39:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MAYORIGUAL);
            }
            // fall through
          case 145: break;
          case 40:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.AS);
            }
            // fall through
          case 146: break;
          case 41:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.DO);
            }
            // fall through
          case 147: break;
          case 42:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.IF);
            }
            // fall through
          case 148: break;
          case 43:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.OR);
            }
            // fall through
          case 149: break;
          case 44:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.TO);
            }
            // fall through
          case 150: break;
          case 45:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.AND);
            }
            // fall through
          case 151: break;
          case 46:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.AUMENTO);
            }
            // fall through
          case 152: break;
          case 47:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.DISMINUCION);
            }
            // fall through
          case 153: break;
          case 48:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.COMPARADOR);
            }
            // fall through
          case 154: break;
          case 49:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.IN);
            }
            // fall through
          case 155: break;
          case 50:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PY);
            }
            // fall through
          case 156: break;
          case 51:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.VB);
            }
            // fall through
          case 157: break;
          case 52:
            { if(cadena.length() > 0){
                                                    String lexema = cadena.toString();
                                                    cadena.setLength(0);
                                                    yypushback(yylength());
                                                    return symbol(yyline+1, (yycolumn+1)-lexema.length(), lexema, sym.CADENA);
                                                }else{
                                                    return symbol(yyline+1, yycolumn+1, yytext(), sym.COMODIN_CARACTER); 
                                                }
            }
            // fall through
          case 158: break;
          case 53:
            { if(cadena.length() > 0){
                                                    String lexema = cadena.toString();
                                                    cadena.setLength(0);
                                                    yypushback(yylength());
                                                    return symbol(yyline+1, (yycolumn+1)-lexema.length(), lexema, sym.CADENA);
                                                }else{
                                                    return symbol(yyline+1, yycolumn+1, yytext(), sym.COMODIN_ENTERO); 
                                                }
            }
            // fall through
          case 159: break;
          case 54:
            { if(cadena.length() > 0){
                                                    String lexema = cadena.toString();
                                                    cadena.setLength(0);
                                                    yypushback(yylength());
                                                    return symbol(yyline+1, (yycolumn+1)-lexema.length(), lexema, sym.CADENA);
                                                }else{
                                                    return symbol(yyline+1, yycolumn+1, yytext(), sym.COMODIN_FLOTANTE); 
                                                }
            }
            // fall through
          case 160: break;
          case 55:
            { if(cadena.length() > 0){
                                                    String lexema = cadena.toString();
                                                    cadena.setLength(0);
                                                    yypushback(yylength());
                                                    return symbol(yyline+1, (yycolumn+1)-lexema.length(), lexema, sym.CADENA);
                                                }else{
                                                    return symbol(yyline+1, yycolumn+1, yytext(), sym.PY); 
                                                }
            }
            // fall through
          case 161: break;
          case 56:
            { if(cadena.length() > 0){
                                                    String lexema = cadena.toString();
                                                    cadena.setLength(0);
                                                    yypushback(yylength());
                                                    return symbol(yyline+1, (yycolumn+1)-lexema.length(), lexema, sym.VB);
                                                }else{
                                                    return symbol(yyline+1, yycolumn+1, yytext(), sym.VB); 
                                                }
            }
            // fall through
          case 162: break;
          case 57:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.CARACTER);
            }
            // fall through
          case 163: break;
          case 58:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.FLOTANTE);
            }
            // fall through
          case 164: break;
          case 59:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.DIM);
            }
            // fall through
          case 165: break;
          case 60:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.END);
            }
            // fall through
          case 166: break;
          case 61:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.FOR);
            }
            // fall through
          case 167: break;
          case 62:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.SUB);
            }
            // fall through
          case 168: break;
          case 63:
            { return symbol(yyline+1, yycolumn+1, yytext().substring(1,2), sym.CARACTER);
            }
            // fall through
          case 169: break;
          case 64:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PR_ENTERO);
            }
            // fall through
          case 170: break;
          case 65:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.DEF);
            }
            // fall through
          case 171: break;
          case 66:
            { return symbol(yyline+1, yycolumn+1, "%%VB", sym.SEPARADOR_VB);
            }
            // fall through
          case 172: break;
          case 67:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.CASE);
            }
            // fall through
          case 173: break;
          case 68:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PR_CARACTER);
            }
            // fall through
          case 174: break;
          case 69:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.ELSE);
            }
            // fall through
          case 175: break;
          case 70:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.LOOP);
            }
            // fall through
          case 176: break;
          case 71:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.NEXT);
            }
            // fall through
          case 177: break;
          case 72:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.STEP);
            }
            // fall through
          case 178: break;
          case 73:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.THEN);
            }
            // fall through
          case 179: break;
          case 74:
            { seccionActual=2; yybegin(PYTHON); return symbol(yyline+1, yycolumn+1, "%%PY", sym.SEPARADOR_PY);
            }
            // fall through
          case 180: break;
          case 75:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.VOID);
            }
            // fall through
          case 181: break;
          case 76:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.ELIF);
            }
            // fall through
          case 182: break;
          case 77:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PASS);
            }
            // fall through
          case 183: break;
          case 78:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.JAVA);
            }
            // fall through
          case 184: break;
          case 79:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MAIN);
            }
            // fall through
          case 185: break;
          case 80:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.WHILE);
            }
            // fall through
          case 186: break;
          case 81:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.BREAK);
            }
            // fall through
          case 187: break;
          case 82:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.CLASS);
            }
            // fall through
          case 188: break;
          case 83:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PR_FLOTANTE);
            }
            // fall through
          case 189: break;
          case 84:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.THIS);
            }
            // fall through
          case 190: break;
          case 85:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MENSAJE);
            }
            // fall through
          case 191: break;
          case 86:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.RANGE);
            }
            // fall through
          case 192: break;
          case 87:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.CONST);
            }
            // fall through
          case 193: break;
          case 88:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.ESPERAR_TECLA);
            }
            // fall through
          case 194: break;
          case 89:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.SCANF);
            }
            // fall through
          case 195: break;
          case 90:
            { if(cadena.length() > 0){
                                                    String lexema = cadena.toString();
                                                    cadena.setLength(0);
                                                    yypushback(yylength());
                                                    return symbol(yyline+1, (yycolumn+1)-lexema.length(), lexema, sym.CADENA);
                                                }else{
                                                    return symbol(yyline+1, yycolumn+1, yytext(), sym.JAVA); 
                                                }
            }
            // fall through
          case 196: break;
          case 91:
            { seccionActual=1; yybegin(JAVA); return symbol(yyline+1, yycolumn+1, "%%JAVA", sym.SEPARADOR_JAVA);
            }
            // fall through
          case 197: break;
          case 92:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.ELSEIF);
            }
            // fall through
          case 198: break;
          case 93:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PUBLIC);
            }
            // fall through
          case 199: break;
          case 94:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.RETURN);
            }
            // fall through
          case 200: break;
          case 95:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.SELECT);
            }
            // fall through
          case 201: break;
          case 96:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.SWITCH);
            }
            // fall through
          case 202: break;
          case 97:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.LIMPIAR_PANTALLA);
            }
            // fall through
          case 203: break;
          case 98:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.PRINTF);
            }
            // fall through
          case 204: break;
          case 99:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.DEFAULT);
            }
            // fall through
          case 205: break;
          case 100:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.MENSAJELN);
            }
            // fall through
          case 206: break;
          case 101:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.INCLUDE);
            }
            // fall through
          case 207: break;
          case 102:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.FUNCTION);
            }
            // fall through
          case 208: break;
          case 103:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.INTINPUT);
            }
            // fall through
          case 209: break;
          case 104:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.CHARINPUT);
            }
            // fall through
          case 210: break;
          case 105:
            { return symbol(yyline+1, yycolumn+1, yytext(), sym.FLOATINPUT);
            }
            // fall through
          case 211: break;
          case 106:
            { seccionActual=3; yybegin(PRINCIPAL); return symbol(yyline+1, yycolumn+1, "%%PROGRAMA", sym.SEPARADOR_PROGRAMA);
            }
            // fall through
          case 212: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
